### ISSUE TITLE
Fix issue with production build

### ISSUE THREAD

**Issue by lukemelia** [collectrium/ember-range-slider#3]
```
➜  ember-range-slider git:(master) ember github-pages:commit --message "Initial gh-pages release"
version: 1.13.13
Command failed: /bin/sh -c ember build --environment=production
File: assets/vendor.js
Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at Object.before (eval at <anonymous> (/Users/lmelia/p/ember/ember-range-slider/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/tools/node.js:24:4), <anonymous>)
    at AST_Node.eval [as transform] (eval at <anonymous> (/Users/lmelia/p/ember/ember-range-slider/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2877:35)
    at eval (eval at <anonymous> (/Users/lmelia/p/ember/ember-range-slider/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:3012:31)
    at AST_Node.eval [as transform] (eval at <anonymous> (/Users/lmelia/p/ember/ember-range-slider/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2881:21)
    at eval (eval at <anonymous> (/Users/lmelia/p/ember/ember-range-slider/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:3012:31)
    at AST_Node.eval [as transform] (eval at <anonymous> (/Users/lmelia/p/ember/ember-range-slider/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2881:21)
    at eval (eval at <anonymous> (/Users/lmelia/p/ember/ember-range-slider/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:3012:31)
    at AST_Node.eval [as transform] (eval at <anonymous> (/Users/lmelia/p/ember/ember-range-slider/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2881:21)
    at eval (eval at <anonymous> (/Users/lmelia/p/ember/ember-range-slider/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:3012:31)
    at AST_Node.eval [as transform] (eval at <anonymous> (/Users/lmelia/p/ember/ember-range-slider/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2881:21)
```

**Comment by lukemelia** [comment]
This seems to have been an issue with my local bower cache.
